// Generated by TanStack Router.
import { Route as rootRoute } from './routes/__root'
import { Route as indexRoute } from './routes/index'
import { Route as contactsRoute } from './routes/contacts/index'
import { Route as contactRoute } from './routes/contacts/$contactId'

export default [rootRoute, indexRoute, contactsRoute, contactRoute]
export const routeTree = [rootRoute, indexRoute, contactsRoute, contactRoute]
