/**
 * Indexes `examples/**\/*.tsx` into `.generated/examples.ts` (the live components) and
 * `.generated/example-sources.json` (their source, as a reader copies it). A page shows an
 * example with `<Example name="ui/actions/button/hierarchy" />`: the preview and the code
 * under it come from the same file, so they can't disagree.
 *
 * The code shown is the example's slice (`extract-example.ts`): its export and the helpers
 * and imports it uses. Each slice is also written to `.generated/examples/`, which the
 * app's typecheck includes, so a slice that wouldn't work when copied fails the build.
 *
 *   node scripts/generate-examples.ts
 */
import { globSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { extractExample } from './extract-example.ts'

const app = resolve(import.meta.dirname, '..')
const dir = join(app, 'examples')
const outDir = join(app, '.generated')
const snippetDir = join(outDir, 'examples')

const files = globSync('**/*.tsx', { cwd: dir }).sort()
const names = files.map((file) =>
  file
    .replace(/\.tsx$/, '')
    .split(sep)
    .join('/'),
)

for (const file of files) {
  const source = readFileSync(join(dir, file), 'utf8')
  if (!source.startsWith("'use client'")) {
    throw new Error(`examples/${file} must start with 'use client' (it renders in the browser).`)
  }
  if (!/^export default function \w+/m.test(source)) {
    throw new Error(`examples/${file} must have an \`export default function\`.`)
  }
}

const imports = names.map(
  (name, index) => `import e${String(index)} from '${relative(outDir, join(dir, name))}'`,
)
const entries = names.map((name, index) => `  '${name}': e${String(index)},`)

mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, 'examples.ts'),
  [
    '// Generated by scripts/generate-examples.ts. Do not edit.',
    "import type { ComponentType } from 'react'",
    ...imports,
    '',
    'export const examples: Record<string, ComponentType> = {',
    ...entries,
    '}',
    '',
  ].join('\n'),
)

rmSync(snippetDir, { recursive: true, force: true })
const sources: Record<string, string> = {}
for (const [index, name] of names.entries()) {
  const file = join(dir, files[index] ?? '')
  const code = await extractExample(file, readFileSync(file, 'utf8'), 'default')
  sources[name] = code
  const snippet = join(snippetDir, `${name}.tsx`)
  mkdirSync(dirname(snippet), { recursive: true })
  writeFileSync(
    snippet,
    `// Generated from examples/${name}.tsx by scripts/generate-examples.ts. Do not edit.\n${code}`,
  )
}
writeFileSync(join(outDir, 'example-sources.json'), `${JSON.stringify(sources, null, 2)}\n`)
console.log(`examples: ${String(names.length)}`)
