/**
 * Writes the reference pages (ADR 0029): one MDX page per component, field, layout and hook,
 * built from the code it documents. Nothing on these pages is written by hand in `apps/docs`:
 *
 * - the path and title come from the stories file's `title` (`UI/Actions/Button` is
 *   `ui/actions/button`, titled "Button");
 * - the description is the owner's TSDoc summary, and the lead and any further sections are its
 *   `@remarks`;
 * - the examples are its stories tagged `docs` (`<Examples of>`, ADR 0028);
 * - an `@example` with a title (`@example In a schema`) becomes a section of that name;
 * - a bound field gets its kind, shorthand and export from the default kit, and its value and
 *   empty value from `@value` and `@empty`;
 * - the API section lists the signature of each function and the props of each export from
 *   `api.json`, and the component tokens from `tokens.json`.
 *
 * A page is written beside the hand-written ones in `content/docs` and is gitignored. A
 * hand-written page at the same path (one without the generated header) wins, as the escape
 * hatch for a reference page that needs more than `@remarks` holds.
 *
 *   node scripts/generate-pages.ts
 */
import { existsSync, globSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve, sep } from 'node:path'
import ts from 'typescript'
import type { ApiEntry } from './generate-api.ts'
import { docsStoriesFiles, titleToPath, unwrapLines } from './stories-examples.ts'

const app = resolve(import.meta.dirname, '..')
const repo = resolve(app, '../..')
const contentDir = join(app, 'content/docs')
const HEADER = '{/* Generated by scripts/generate-pages.ts from the TSDoc and stories of'

const api = JSON.parse(readFileSync(join(app, '.generated/api.json'), 'utf8')) as Record<
  string,
  ApiEntry
>
const tokens = JSON.parse(readFileSync(join(app, '.generated/tokens.json'), 'utf8')) as {
  components: Record<string, unknown[] | undefined>
}

/** The groups of the ADR 0010 tree whose pages document one export each. */
const REFERENCE =
  /^(UI\/(Actions|Inputs|Layout|Display|Navigation|Feedback|Overlays|Typography)|Forms\/(Fields|Layouts|Hooks))\//

/** `text: FormTextField` in the default kit, read from source: export → kind. */
function fieldKinds(): Map<string, string> {
  const file = join(repo, 'packages/forms/src/components/fields/defaultFields.ts')
  const source = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.ESNext, true)
  const kinds = new Map<string, string>()
  const visit = (node: ts.Node) => {
    if (ts.isPropertyAssignment(node) && ts.isIdentifier(node.initializer)) {
      kinds.set(node.initializer.text, node.name.getText())
    }
    ts.forEachChild(node, visit)
  }
  visit(source)
  return kinds
}

/** Escapes `|` for a Markdown table cell. */
const cell = (text: string) => text.replaceAll('|', '\\|')

/** `text` → `TextField`, as the kit names a field (`fieldComponentName` in kiln-forms). */
const shorthand = (kind: string) => `${kind.charAt(0).toUpperCase()}${kind.slice(1)}Field`

/** The page that documents each export, for `{@link}`. */
const pageOf = new Map<string, string>()

interface Page {
  path: string
  title: string
  owner: ApiEntry
  of: string
  exports: ApiEntry[]
  stories: number
}

const pages: Page[] = []
for (const { of, file, title, stories } of docsStoriesFiles(repo)) {
  if (!REFERENCE.test(title) || /^packages\/[^/]+\/src\/(docs|stories)\//.test(file)) continue
  const owner = api[of]
  if (!owner) throw new Error(`${file}: ${of} isn't a public export, so it can't own a page.`)
  // A component's page documents what its folder exports (`getInitials` beside `Avatar`); a
  // hook in the flat hooks folder owns only its own file. Types and plain constants are listed
  // in the API tables, not as exports of the page.
  const folder = dirname(owner.file)
  const index = join(repo, folder, 'index.ts')
  const fromFolder = folder.endsWith(`/${of}`) && existsSync(index) ? folderExports(index) : []
  const exports = [
    owner,
    ...Object.values(api).filter(
      (entry) =>
        entry !== owner &&
        (entry.kind === 'component' || entry.kind === 'function') &&
        (fromFolder.length ? fromFolder.includes(entry.name) : entry.file === owner.file),
    ),
  ]
  const path = titleToPath(title)
  for (const entry of exports) pageOf.set(entry.name, path)
  pages.push({
    path,
    title: title.split('/').at(-1) ?? of,
    owner,
    of,
    exports,
    stories: stories.length,
  })
}

/** The names a folder's `index.ts` exports: `export { Field } from './Field'`. */
function folderExports(file: string): string[] {
  const names: string[] = []
  for (const [, list = ''] of readFileSync(file, 'utf8').matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const item of list.split(',')) {
      const name = item
        .trim()
        .replace(/^type\s+/, '')
        .split(/\s+as\s+/)
        .at(-1)
        ?.trim()
      if (name) names.push(name)
    }
  }
  return names
}

// Hand-written pages document exports too: `{@link}` can point at them.
function frontmatterExports(text: string): string[] {
  const match = /^---\n([\s\S]*?)\n---/.exec(text)
  const list = /exports:\s*\[([^\]]*)\]/.exec(match?.[1]?.replace(/\n\s*/g, ' ') ?? '')?.[1]
  return list
    ? list
        .split(',')
        .map((name) => name.trim())
        .filter(Boolean)
    : []
}

/** `{@link X}`, `{@link X | text}` and `{@link @pkg#X | text}` as Markdown links to X's page. */
function links(markdown: string): string {
  return markdown.replace(
    /\{@link\s+([^}|\s]+)\s*(?:\|\s*([^}]+))?\}/g,
    (_, target: string, text?: string) => {
      const name = target.replace(/^.*#/, '')
      const label = text?.trim() ?? `\`${name}\``
      const page = pageOf.get(name)
      return page ? `[${label}](/docs/${page})` : label
    },
  )
}

/** `@remarks` split into the lead (before its first `##`) and the sections after it. */
function splitRemarks(remarks: string): { lead: string; sections: string } {
  const at = remarks.search(/^## /m)
  return at < 0
    ? { lead: remarks, sections: '' }
    : { lead: remarks.slice(0, at), sections: remarks.slice(at) }
}

const kinds = fieldKinds()

function render(page: Page): string {
  const { owner } = page
  if (!owner.description) {
    throw new Error(`${owner.name} has no TSDoc summary: it's the description of its page.`)
  }
  if (page.stories === 0) throw new Error(`${owner.name} has no stories tagged docs.`)
  const { lead, sections } = splitRemarks(owner.remarks ?? '')
  const out: string[] = [
    '---',
    `title: ${page.title}`,
    `description: ${JSON.stringify(owner.description.replace(/\s*\n\s*/g, ' '))}`,
    `exports: [${page.exports.map((entry) => entry.name).join(', ')}]`,
    '---',
    '',
    `${HEADER} ${owner.name}. Edit those. */}`,
    '',
  ]
  if (owner.deprecated !== undefined) {
    out.push(
      `<Callout title="Deprecated">${links(owner.deprecated) || 'Deprecated.'}</Callout>`,
      '',
    )
  }
  if (lead.trim()) out.push(unwrapLines(links(lead.trim())), '')
  const kind = kinds.get(owner.name)
  if (kind) {
    if (!owner.value || !owner.empty) {
      throw new Error(
        `${owner.name} needs \`@value\` and \`@empty\` in its TSDoc for its field table.`,
      )
    }
    out.push(
      '| Kind | Shorthand | Export | Value | Empty |',
      '| --- | --- | --- | --- | --- |',
      `| \`${kind}\` | \`form.${shorthand(kind)}\` | \`${owner.name}\` | ${cell(owner.value)} | ${cell(owner.empty)} |`,
      '',
    )
  }
  out.push(`<Examples of="${page.of}" />`, '')
  if (sections.trim()) out.push(unwrapLines(links(sections.trim())), '')
  for (const example of owner.examples ?? []) {
    if (!example.title) continue
    out.push(`## ${example.title}`, '', unwrapLines(links(example.body.trim())), '')
  }
  out.push('## API', '')
  if (kind) {
    out.push(
      'Every bound field also takes `name` (a path to a value it can hold), `validators`, `listeners` and `defaultValue`, plus `warn` for advice that never blocks. `excluded` keeps a field visible but leaves it out of validation and submits its default.',
      '',
    )
  }
  for (const entry of page.exports) {
    if (entry.kind === 'function') out.push(`<ApiSignature of="${entry.name}" />`, '')
  }
  const tables = apiTables(page)
  if (tables.length) out.push(`<ApiTable of="${tables.join(', ')}" />`, '')
  for (const entry of page.exports) {
    if (!tokens.components[entry.name]) continue
    out.push(
      '### Component tokens',
      '',
      'Set these in a theme, or on one element, to change this component without touching the rest.',
      '',
      `<ComponentTokens of="${entry.name}" />`,
      '',
    )
  }
  return `${out.join('\n').trimEnd()}\n`
}

/**
 * The API tables of a page: each export's `<Name>Props` and its compound parts' props, the
 * object types those props use (`SegmentedControlOption`), and the types its functions take and
 * return (`AutosaveOptions`), leaving out their type parameters' constraints.
 */
function apiTables(page: Page): string[] {
  const names: string[] = []
  const isTable = (name: string) => api[name]?.kind === 'type' && !names.includes(name)
  // `AnyKitForm` and its kind are constraints for any form, not shapes a reader builds.
  const shape = (name: string) => Boolean(api[name]?.props?.length) && !/^Any[A-Z]/.test(name)
  const addProps = (name: string) => {
    if (isTable(name)) names.push(name)
  }
  for (const entry of page.exports) {
    addProps(`${entry.name}Props`)
    for (const member of entry.members ?? []) addProps(`${entry.name}${member}Props`)
  }
  for (const table of [...names]) {
    for (const prop of api[table]?.props ?? []) {
      for (const [name] of prop.type.matchAll(/\b[A-Z]\w+\b/g)) {
        if (isTable(name) && shape(name)) names.push(name)
      }
    }
  }
  for (const entry of page.exports) {
    if (entry.kind !== 'function' || !entry.signature) continue
    const signature = entry.signature.replace(
      new RegExp(`^declare function ${entry.name}<[^(]*>`),
      '',
    )
    for (const [name] of signature.matchAll(/\b[A-Z]\w+\b/g)) {
      if (isTable(name) && shape(name)) names.push(name)
    }
  }
  return names
}

const generated = new Set(pages.map((page) => `${page.path}.mdx`))
const files = globSync('**/*.mdx', { cwd: contentDir })
  .map((file) => file.split(sep).join('/'))
  .sort()
for (const file of files) {
  const text = readFileSync(join(contentDir, file), 'utf8')
  // A generated page left behind by a stories file that moved or went.
  if (text.includes(HEADER) && !generated.has(file)) {
    rmSync(join(contentDir, file))
    continue
  }
  if (text.includes(HEADER)) continue
  for (const name of frontmatterExports(text)) {
    if (!pageOf.has(name)) pageOf.set(name, file.replace(/(\/index)?\.mdx$/, ''))
  }
}

let written = 0
for (const page of pages) {
  const file = join(contentDir, `${page.path}.mdx`)
  if (existsSync(file) && !readFileSync(file, 'utf8').includes(HEADER)) continue
  writeFileSync(file, render(page))
  written++
}
console.log(`pages: ${String(written)} reference pages`)
