/**
 * Indexes the docs examples into `.generated/examples.ts` (the live components),
 * `.generated/example-sources.json` (their source, as a reader copies it) and
 * `.generated/example-docs.json` (the docs stories of each stories file, for `<Examples of>`).
 * All three are keyed by the id `exampleId` in `src/lib/examples.ts` reads:
 *
 * - `Button#Hierarchy` is the `Hierarchy` story of `Button.stories.tsx`, tagged `docs`
 *   (`stories-examples.ts`, ADR 0028). A page shows it with
 *   `<Example of="Button" name="Hierarchy" />`.
 *
 * The code shown is the example's slice (`extract-example.ts`): its component and the helpers
 * and imports it uses. Each slice is written to `.generated/examples/`, which the app's
 * typecheck includes, so a slice that wouldn't work when copied fails the build, and the live
 * preview renders that same slice, so the preview is the code shown.
 *
 *   node scripts/generate-examples.ts
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { extractExample } from './extract-example.ts'
import { docsStoriesFiles, type DocsStory } from './stories-examples.ts'

const app = resolve(import.meta.dirname, '..')
const repo = resolve(app, '../..')
const outDir = join(app, '.generated')
const snippetDir = join(outDir, 'examples')

/** One live example: where it's read from, and the file its slice is written to. */
interface Entry {
  id: string
  file: string
  exportName: string
  snippet: string
  /** The stories file read as an examples file, which the slice is cut from. */
  text: string
}

/** An import path from `from` (a file) to `to`, without the extension. */
function importPath(from: string, to: string): string {
  const path = relative(dirname(from), to.replace(/\.tsx$/, ''))
    .split(sep)
    .join('/')
  return path.startsWith('.') ? path : `./${path}`
}

const entries: Entry[] = []
const owners = new Map<string, string>()

function own(of: string, file: string) {
  const other = owners.get(of)
  if (other) throw new Error(`${other} and ${file} are both the examples of ${of}.`)
  owners.set(of, file)
}

/** The docs stories of each stories file, in file order, for `<Examples of>`. */
const docs: Record<string, DocsStory[]> = {}
for (const { of, file, stories, examples } of docsStoriesFiles(repo)) {
  own(of, file)
  docs[of] = stories
  for (const { name } of stories) {
    entries.push({
      id: `${of}#${name}`,
      file: join(repo, file),
      exportName: name,
      snippet: `${of}.${name}.tsx`,
      text: examples,
    })
  }
}

// Each slice carries 'use client' (the packages don't, ADR 0019), so the registry is a list of
// client references and a page loads only the examples it shows.
rmSync(snippetDir, { recursive: true, force: true })
const sources: Record<string, string> = {}
const imports: string[] = []
for (const [index, { id, file, exportName, snippet, text }] of entries.entries()) {
  const code = await extractExample(file, text, exportName)
  sources[id] = code
  const out = join(snippetDir, snippet)
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(
    out,
    `// Generated from ${relative(repo, file).split(sep).join('/')} by scripts/generate-examples.ts. Do not edit.\n'use client'\n\n${code}`,
  )
  imports.push(
    `import { ${exportName} as e${String(index)} } from '${importPath(join(outDir, 'examples.ts'), out)}'`,
  )
}

mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, 'examples.ts'),
  [
    '// Generated by scripts/generate-examples.ts. Do not edit.',
    "import type { ComponentType } from 'react'",
    ...imports,
    '',
    'export const examples: Record<string, ComponentType> = {',
    ...entries.map(({ id }, index) => `  '${id}': e${String(index)},`),
    '}',
    '',
  ].join('\n'),
)
writeFileSync(join(outDir, 'example-sources.json'), `${JSON.stringify(sources, null, 2)}\n`)
writeFileSync(join(outDir, 'example-docs.json'), `${JSON.stringify(docs, null, 2)}\n`)
console.log(
  `examples: ${String(entries.length)} (${String(Object.values(docs).flat().length)} docs stories)`,
)
