/**
 * Writes the Design rules page from DESIGN.md §1 (principles) and §2 (the anti-slop rules),
 * so the site, the `design-rules` agent skill and the binding standard are one text.
 * The page is generated and gitignored: edit DESIGN.md, never the page.
 *
 *   node scripts/generate-design-rules.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '../../..')
const out = resolve(import.meta.dirname, '../content/docs/ui/foundations/design-rules.mdx')

const design = readFileSync(resolve(root, 'DESIGN.md'), 'utf8')

/** A numbered `## N. Title` section of DESIGN.md, up to the next `---` rule. */
function section(number: string): string {
  const match = new RegExp(`^## ${number}\\. [^\\n]*\\n([\\s\\S]*?)\\n---\\n`, 'm').exec(design)
  if (!match) throw new Error(`DESIGN.md has no section ${number} followed by a --- rule`)
  // §-references to the rules point at their heading on the page instead.
  return (match[1] ?? '').trim().replace(/\(see §2\)/g, '(see [Not AI slop](#not-ai-slop))')
}

const page = `---
title: Design rules
description: The principles and anti-slop rules every Kiln component, theme, example and screen follows.
---

{/* Generated by scripts/generate-design-rules.ts from DESIGN.md §1 and §2. Edit DESIGN.md, not this file. */}

These rules come from [DESIGN.md](https://github.com/mitcsutt/kiln/blob/main/DESIGN.md), which is binding for everything in the Kiln repository. They apply just as well to screens you build with Kiln: the components and tokens make most of them the default, and the rest are a review checklist.

## Principles

${section('1')}

## Not AI slop

${section('2')}
`

writeFileSync(out, page)
console.log('design-rules.mdx: DESIGN.md §1 and §2')
