/**
 * Indexes the docs examples into `.generated/examples.ts` (the live components) and
 * `.generated/example-sources.json` (their source, as a reader copies it). The preview and the
 * code under it come from the same file, so they can't disagree. Both are keyed by the id
 * `exampleId` in `src/lib/examples.ts` reads:
 *
 * `Button#Hierarchy` is the `Hierarchy` export of the `*.examples.tsx` file beside `Button`
 * (`examples-files.ts`), which a page shows with `<Example of="Button" name="Hierarchy" />`.
 *
 * The code shown is the example's slice (`extract-example.ts`): its export and the helpers
 * and imports it uses. Each slice is also written to `.generated/examples/`, which the
 * app's typecheck includes, so a slice that wouldn't work when copied fails the build.
 *
 *   node scripts/generate-examples.ts
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { examplesFiles } from './examples-files.ts'
import { exampleNames, extractExample } from './extract-example.ts'

const app = resolve(import.meta.dirname, '..')
const repo = resolve(app, '../..')
const outDir = join(app, '.generated')
const snippetDir = join(outDir, 'examples')
const clientDir = join(outDir, 'client')

/** One live example: where it's read from, and the file its slice is written to. */
interface Entry {
  id: string
  file: string
  exportName: string
  snippet: string
}

/** An import path from `from` (a file) to `to`, without the extension. */
function importPath(from: string, to: string): string {
  const path = relative(dirname(from), to.replace(/\.tsx$/, ''))
    .split(sep)
    .join('/')
  return path.startsWith('.') ? path : `./${path}`
}

const entries: Entry[] = []
const imports: string[] = []

// An examples file carries no 'use client' (ADR 0025), so each gets a generated client module
// that re-exports its examples, and the registry imports them from there. A page then loads
// only the examples it shows.
rmSync(clientDir, { recursive: true, force: true })
for (const { of, file } of examplesFiles(repo)) {
  const path = join(repo, file)
  const names = exampleNames(path, readFileSync(path, 'utf8'))
  if (names.length === 0) throw new Error(`${file} exports no examples.`)
  if (names.includes('default')) {
    throw new Error(`${file} has a default export. Name each example (\`Usage\` by default).`)
  }
  const client = join(clientDir, `${of}.tsx`)
  mkdirSync(dirname(client), { recursive: true })
  writeFileSync(
    client,
    [
      `// Generated from ${file} by scripts/generate-examples.ts. Do not edit.`,
      "'use client'",
      '',
      `export { ${names.join(', ')} } from '${importPath(client, path)}'`,
      '',
    ].join('\n'),
  )
  const locals = names.map((name, index) => `${name} as e${String(entries.length + index)}`)
  imports.push(
    `import { ${locals.join(', ')} } from '${importPath(join(outDir, 'examples.ts'), client)}'`,
  )
  for (const name of names) {
    entries.push({
      id: `${of}#${name}`,
      file: path,
      exportName: name,
      snippet: `${of}.${name}.tsx`,
    })
  }
}

mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, 'examples.ts'),
  [
    '// Generated by scripts/generate-examples.ts. Do not edit.',
    "import type { ComponentType } from 'react'",
    ...imports,
    '',
    'export const examples: Record<string, ComponentType> = {',
    ...entries.map(({ id }, index) => `  '${id}': e${String(index)},`),
    '}',
    '',
  ].join('\n'),
)

rmSync(snippetDir, { recursive: true, force: true })
const sources: Record<string, string> = {}
for (const { id, file, exportName, snippet } of entries) {
  const code = await extractExample(file, readFileSync(file, 'utf8'), exportName)
  sources[id] = code
  const out = join(snippetDir, snippet)
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(
    out,
    `// Generated from ${relative(repo, file).split(sep).join('/')} by scripts/generate-examples.ts. Do not edit.\n${code}`,
  )
}
writeFileSync(join(outDir, 'example-sources.json'), `${JSON.stringify(sources, null, 2)}\n`)
console.log(`examples: ${String(entries.length)}`)
