import { kit } from '@mitcsutt/kiln-forms'
import { parseFormSchema } from '@mitcsutt/kiln-forms/schema'
import { allApi, getApi } from '@/lib/api'
import { contentPages } from './content'

// ADR 0029: a reference page is written from its owner's TSDoc and stories, so the TSDoc is
// public copy. These checks keep it fit to publish.

const pages = contentPages()
const generated = pages.filter(({ body }) =>
  body.includes('Generated by scripts/generate-pages.ts'),
)

describe('the reference pages', () => {
  it('are generated, one per component, field, layout and hook', () => {
    expect(generated.length).toBeGreaterThan(150)
  })

  it('each describe their owner in its TSDoc summary', () => {
    const missing = generated.filter(({ frontmatter }) => !frontmatter.description)
    expect(missing.map(({ path }) => path)).toEqual([])
  })
})

/** Every export whose doc comments a page shows: owners, API tables and signatures. */
function shown(): Set<string> {
  const names = new Set<string>()
  for (const { body, frontmatter } of pages) {
    for (const [, list = ''] of body.matchAll(/<Api(?:Table|Signature)\b[^>]*\bof="([^"]+)"/g)) {
      for (const name of list.split(',')) names.add(name.trim())
    }
    if (body.includes('Generated by scripts/generate-pages.ts')) {
      for (const name of frontmatter.exports ?? []) names.add(name)
    }
  }
  return names
}

describe('the TSDoc the docs show', () => {
  // `§` cites the maintainers' design reference (packages/forms/docs/design.md). It belongs in
  // `@privateRemarks` or a `//` comment, not in what a page shows.
  it('has no references to the design document', () => {
    const found: string[] = []
    for (const name of shown()) {
      const entry = getApi(name)
      const texts = [
        entry.description,
        entry.remarks ?? '',
        ...(entry.examples ?? []).map((example) => example.body),
        ...(entry.props ?? []).map((prop) => prop.description),
      ]
      if (texts.some((text) => text.includes('§'))) found.push(name)
    }
    expect(found).toEqual([])
  })

  it('gives every bound field the value it holds and its empty value', () => {
    const fields = allApi().filter((entry) => /^Form\w+Field$/.test(entry.name))
    expect(fields.length).toBeGreaterThan(20)
    expect(fields.filter((entry) => !entry.value || !entry.empty).map(({ name }) => name)).toEqual(
      [],
    )
  })
})

describe('the "In a schema" examples', () => {
  const examples = allApi().flatMap((entry) =>
    (entry.examples ?? [])
      .filter((example) => example.title === 'In a schema' && example.body.includes('```json'))
      .map((example) => ({ name: entry.name, body: example.body })),
  )

  it('are found', () => {
    expect(examples.length).toBeGreaterThan(40)
  })

  it.each(examples)('$name parses with parseFormSchema', ({ body }) => {
    const root: unknown = JSON.parse(/```json\n([\s\S]*?)\n```/.exec(body)?.[1] ?? '')
    // `stops` is the options loader the examples' app registers (`optionsFrom: { loader }`).
    const result = parseFormSchema(
      { version: 1, root },
      { kinds: Object.keys(kit.registries.fields), loaders: ['stops'] },
    )
    expect(result.ok ? [] : result.issues).toEqual([])
  })
})
